use serde::{Deserialize, Serialize};

/// The type of promo for a card.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[allow(missing_docs)]
pub enum PromoType {
    ArenaLeague,
    BoosterFun,
    BoxTopper,
    BrawlDeck,
    BringAFriend,
    Bundle,
    BuyABox,
    Convention,
    DateStamped,
    DraculaSeries,
    DraftWeekend,
    Duels,
    Event,
    Fnm,
    GalaxyFoil,
    GameDay,
    Gateway,
    GiftBox,
    Gilded,
    Glossy,
    GodzillaSeries,
    InStore,
    IntroPack,
    JpWalker,
    JudgeGift,
    League,
    MediaInsert,
    NeonInk,
    OpenHouse,
    PlaneswalkerStamped,
    PlayerRewards,
    PlayPromo,
    PremiereShop,
    Prerelease,
    PromoPack,
    Release,
    SChineseAltArt,
    SetPromo,
    Stamped,
    SurgeFoil,
    Textured,
    ThemePack,
    Thick,
    Tourney,
    WizardsPlayNetwork,
}
